### ISSUE TITLE
Fields in additional_info encoded as string instead of integer

### ISSUE THREAD

**Issue by epoupon** [phw/foo_listenbrainz2#12]
According to https://listenbrainz.readthedocs.io/en/latest/users/json.html#fetching-listen-json  `tracknumber` should be encoded as integer.

Looks like LB stores and reports this as is when fetching the listens afterwards, the type is then not the expected, documented one.

**Comment by redactedscribe** [comment]
https://github.com/phw/foo_listenbrainz2/blob/9d2afb3bf26fed46875561cddb20505345f563e4/src/play.cpp#L23-L32
