### ISSUE TITLE
Error with Main menu check

### ISSUE THREAD

**Issue by regorxxx** [phw/foo_listenbrainz2#22]
[SMP has a method to check main menus](https://theqwertiest.github.io/foo_spider_monkey_panel/assets/generated_files/docs/html/fb.html#.IsMainMenuCommandChecked)
It always returns true, even when it's disabled. To be clear, the UI part works fine. The check mark is only shown when enabled.

![image](https://github.com/user-attachments/assets/c08548db-8891-4414-a3de-bd2675dfd19b)

It works fine for any entry but not for the one provided by this component. I have tried with other components and it works fine too... so just reporting in case is something wrong here.

Right now is impossible to check -via JS- if submissions are enabled or not since it always says true.

**Comment by marc2k3** [comment]
> To be clear, the UI part works fine

So there is no bug then.

You as a human should be able to understand this code as does fb2k itself...

https://github.com/phw/foo_listenbrainz2/blob/8d7eb57e920c56b13ae5ae0d3826e2a844c9d857/src/mainmenu.cpp#L25-L31

There is no other way to write that. SMP is the one at fault.

**Comment by phw** [comment]
@marc2k3 thanks for answering
